version: '3.1'
services:
  postgresql10:
    restart: unless-stopped
    image: postgres:12
    ports:
      - "10001:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    networks:
        public:
            ipv4_address: 10.0.1.25
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
      
  odoo:
    image: docker.io/bitnami/odoo:10
    ports:
      - '10002:8069'
    depends_on:
      - postgresql
    volumes:
      - './odoo_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql10
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=odoo
      - ODOO_DATABASE_NAME=bitnami_odoo
      - ODOO_DATABASE_PASSWORD=odoo
      - POSTGRESQL_USER=odoo
      - POSTGRESQL_PASSWORD=odoo
      - POSTGRESQL_HOST=postgresql10
      - POSTGRESQL_PORT=5432
    networks:
        public:
          ipv4_address: 10.0.1.40

networks:
  public:
    external:
      name: public
